layout_spectrum: 0.2055138
typography_spectrum: 0.5362563
color:
  lightness: 0.5725126
  brandStrength: 0.4291737
  saturation: 0.5961214
  rhythmicContrast: 0.737774
  brandColors:
    - '#CFC6BD'
    - '#0C0B0E'
    - '#542717'
    - '#FEFFFE'
    - '#6E6E6F'
name: lipsum
